MyWebApp/Controllers/TB_VideoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyWebApp.Models;
using MyWebApp.Repositories.Authentication;

namespace MyWebApp.Controllers
{
    public class TB_VideoController : RestrictedController
    {
        private personNETEntities db = new personNETEntities();

        // GET: TB_Video
        public ActionResult Index()
        {
            var tB_Video = db.TB_Video.Include(t => t.TB_Content);
            return View(tB_Video.ToList());
        }

        // GET: TB_Video/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TB_Video tB_Video = db.TB_Video.Find(id);
            if (tB_Video == null)
            {
                return HttpNotFound();
            }
            return View(tB_Video);
        }

        // GET: TB_Video/Create
        public ActionResult Create()
        {
            ViewBag.IdContent = new SelectList(db.TB_Content, "IdContent", "ContentType");
            return View();
        }

        [HttpPost]
        [ActionName("Create")]
        public ActionResult Upload(HttpPostedFileBase DirVideo, string title)
        {
            TB_Content tB_Content = new TB_Content
            {
                IdContent = db.TB_Content.Count(),
                ContentType = "Video",
                UploadDate = DateTime.Now,
                ContentViews = 0,
                IdUser = UserControl.VerifyUserStatus().IdUser
            };

            TB_Video tB_Video = new TB_Video();
            tB_Video.Title = title;

            if (DirVideo != null && DirVideo.ContentLength > 0)
            {
                var path = Server.MapPath("~/UserFiles/" + UserControl.VerifyUserStatus().IdUser + "/vid/");

                if (!Directory.Exists(path)) Directory.CreateDirectory(path);
                path = Path.Combine(path, tB_Content.IdContent.ToString() + Path.GetExtension(DirVideo.FileName));
                DirVideo.SaveAs(path);
                tB_Video.DirVideo = "\\" + path.Substring(Server.MapPath("~").Length);
            }

            if (ModelState.IsValid)
            {
                db.TB_Content.Add(tB_Content);

                tB_Video.IdContent = tB_Content.IdContent;

                db.TB_Video.Add(tB_Video);
                db.SaveChanges();
                return Redirect("../MainPage/Index");
            }

            return View(tB_Video);
        }

        // GET: TB_Video/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TB_Video tB_Video = db.TB_Video.Find(id);
            if (tB_Video == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdContent = new SelectList(db.TB_Content, "IdContent", "ContentType", tB_Video.IdContent);
            return View(tB_Video);
        }

        // POST: TB_Video/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdContent,DirVideo,Title")] TB_Video tB_Video)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tB_Video).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdContent = new SelectList(db.TB_Content, "IdContent", "ContentType", tB_Video.IdContent);
            return View(tB_Video);
        }

        // GET: TB_Video/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TB_Video tB_Video = db.TB_Video.Find(id);
            if (tB_Video == null)
            {
                return HttpNotFound();
            }
            return View(tB_Video);
        }

        // POST: TB_Video/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TB_Video tB_Video = db.TB_Video.Find(id);
            db.TB_Video.Remove(tB_Video);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyWebApp/Views/TB_Video/Create.cshtml
@model MyWebApp.Models.TB_Video

@{
    ViewBag.Title = "Postar Vídeo";
}

<h2>Postar Vídeo</h2>

@using (Html.BeginForm("Create", "TB_Video", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    @Html.EditorFor(model => model.DirVideo, new { htmlAttributes = new { @class = "form-control", @type = "file", @value = "Selecionar Arquivo", @accept = "video/*" } })
    @Html.ValidationMessageFor(model => model.DirVideo, "", new { @class = "text-danger" })
    <div><span>Título</span></div>
    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
    <input type="submit" value="Fazer Upload" />

}
<div>
    @Html.ActionLink("Voltar à Página Principal", "Index", "MainPage")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MyWebApp/Views/TB_Video/Delete.cshtml
@model MyWebApp.Models.TB_Video

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TB_Video</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DirVideo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DirVideo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TB_Content.ContentType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TB_Content.ContentType)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MyWebApp/Views/TB_Video/Details.cshtml
@model MyWebApp.Models.TB_Video

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>TB_Video</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DirVideo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DirVideo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TB_Content.ContentType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TB_Content.ContentType)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IdContent }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MyWebApp/Views/TB_Video/Edit.cshtml
@model MyWebApp.Models.TB_Video

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TB_Video</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdContent)

        <div class="form-group">
            @Html.LabelFor(model => model.DirVideo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DirVideo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DirVideo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MyWebApp/Views/TB_Video/Index.cshtml
@model IEnumerable<MyWebApp.Models.TB_Video>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DirVideo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TB_Content.ContentType)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.DirVideo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TB_Content.ContentType)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.IdContent }) |
            @Html.ActionLink("Details", "Details", new { id=item.IdContent }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.IdContent })
        </td>
    </tr>
}

</table>